### ISSUE TITLE
Pull in updated credential management from Moonshot's mech_eap

### ISSUE THREAD

**Issue by jbasney** [fedushare/mech_saml_ec#18]
Storing username/password in ~/.gss_eap_id is not acceptable for production use. Moonshot has improved credential management code that mech_saml_ec should pull in and use.

**Comment by nawatts** [comment]
Per Stephan's recommendation, the username returned by the Moonshot Identity Selector should be split on the last @ symbol instead of the first.

**Comment by nawatts** [comment]
IdP's PAOS URL can be stored in the Moonshot Identity Selector as the identity Issuer. It can then be stored on the GSS credential until it's used by the client instead of having the client read the URL from an environment variable.

**Comment by nawatts** [comment]
* [ ] Add field to `gss_cred_id_struct` in `gssapiP_eap.h`
* [ ] Allocate field in `gssEapAllocCred` in `util_cred.c`
* [ ] Free field in `gssEapReleaseCred` in `util_cred.c`
* [ ] Store field value in `libMoonshotResolveDefaultIdentity` and `libMoonshotResolveInitiatorCred` in `util_moonshot.c`
* [ ] Replace environment variable with field from GSS credential in `processSAMLRequest` in `init_sec_context.c`
