### ISSUE TITLE
support for multiple AssertionConsumerService entries per SP

### ISSUE THREAD

**Issue by jbasney** [fedushare/mech_saml_ec#20]
Possibly related to #17.

For compute clusters with multiple login nodes, we'd like to register an AssertionConsumerService entry for each login node under the same SP entity ID. Currently mech_saml_ec assumes it should use the first PAOS entry it finds. I think some smarter runtime matching of GSS requested principal to PAOS entries is needed to support this use case.

**Comment by nawatts** [comment]
Do all the individual SPs at the individual login nodes need to be aware of each other? Could they just be configured with their own ACS and only the metadata in IdP configuration contain the combined list?

**Comment by jbasney** [comment]
Our admins would like all the nodes to use an identical configuration to fit their current node spin-up procedure across multiple cluster nodes. Also I expect they'd want to use production InCommon metadata, so custom metadata per node is undesirable.

**Comment by spaetow** [comment]
Hmmm, can you do GSS host name matching perhaps, i.e. GSS should provide the GSS acceptor host (i.e. the host that initiates the authN request), so you should be able to go through the PAOS list to see whether there's a match? Just a suggestion... 🎱

**Comment by nawatts** [comment]
It looks like it would only have to be done in [one place](https://github.com/fedushare/mech_saml_ec/blob/438ef5ce09e762155fca1fbb94578ac3b3900be6/mech_saml_ec/SAML2XML.cpp#L207) to get the ACS URL that matches the host name.

That section needs work anyway, for #13 and #17.

**Comment by nawatts** [comment]
@jbasney To make sure I've got this correct, the desired configuration here is two SP nodes, each with identical contents of `/etc/shibboleth/shibboleth2.xml` and a single SP registered with the IdP, which has two copies of each Assertion Consumer Service (one of each type per SP node).

**Comment by nawatts** [comment]
Would all SP nodes use the same keys?

**Comment by nawatts** [comment]
This currently works with two SP nodes using the same `shibboleth2.xml` configuration and the same keys. The SP metadata provided to the IdP lists the single entity ID and one copy of each ACS per node.

**Comment by jbasney** [comment]
@nawatts Yes, that sounds perfect: multiple SP nodes using same `shibboleth.xml` and same keys with an ACS per node (i.e., per hostname) in metadata. The nodes use the same keys because they're considered a single entity (one entityID), and the KeyDescriptor in metadata is associated with the entity. Thanks!

**Comment by nawatts** [comment]
Excellent. That case works without any changes to `mech_saml_ec`.
